 server:
  port: 8090
 
 management:
  endpoints:
    web:
      exposure:
        include: "*"
 course:
  message: Hello world!
 
 spring:
  h2:
   console.enabled: true
   datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 
    driverClassName: org.h2.Driver
    
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  